PGPIDENT="fireflyc"
PYTHON=python
PIP=pip
PIP_DOUBAN = -i http://pypi.douban.com/simple --trusted-host pypi.douban.com

all: help

help:
	@echo "fuck               -囧"
	@echo "dist_3party              download offline "
	@echo "clean                - clean"
	@echo "  clean-pyc          - Remove .pyc/__pycache__ files"
	@echo "  clean-build        - Remove setup artifacts."

fuck:
	$(PIP) install -r requirements.txt $(PIP_DOUBAN)

clean: clean-pyc clean-build

clean-pyc:
	-find . -type f -a \( -name "*.pyc" -o -name "*$$py.class" \) | xargs rm
	-find . -type d -name "__pycache__" | xargs rm -r

clean-build:
	rm -rf build/ dist/ .eggs/ *.egg-info/

test:
	$(PYTHON) setup.py test

build:
	$(PYTHON) setup.py sdist

dist_3party:
	mkdir -p dist/pkg/thirdparty/pipcache
	$(PIP) download -r requirements.txt -d ./dist/pkg/thirdparty/pipcache $(PIP_DOUBAN)
	cp requirements.txt dist/pkg/thirdparty/
	cp dist/python-dpi-*.tar.gz dist/pkg/

dist: clean dist_3party