# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "dev_srv" do |dev_srv|
    dev_srv.vm.box = "ubuntu/trusty64"
    dev_srv.vm.provider "virtualbox" do |vb|
       vb.name = "jumpserver-dev"
       vb.memory = 1024
       vb.cpus = 1
     end
     dev_srv.vm.host_name = "devvsrv"
     dev_srv.vm.network "private_network", ip: "192.168.200.11"
     dev_srv.vm.network "forwarded_port", guest: 8000, host: 8000
     dev_srv.vm.synced_folder "..", "/jumpserver"
     dev_srv.vm.provision "shell", path:"bootstrap_ubuntu.sh"
   end
   
   #config.vm.define "test_srv" do |test_srv|
   # test_srv.vm.box = "centos/7"
   # test_srv.vm.provider "virtualbox" do |vb|
   #     vb.name = "jumpserver-test"
   #     vb.memory = 512
   #     vb.cpus = 1
   # end
   # test_srv.vm.host_name = "testsrv"
   # test_srv.vm.network "private_network", ip: "192.168.200.12"
   #end
end
